-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: adbb569fe9a64ad9bce3b53a77f1bc39ef31f682
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-added-large-files
    -   id: autopep8-wrapper
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: flake8
        language_version: python3
-   repo: git@github.com:asottile/reorder_python_imports.git
    sha: v0.2.0
    hooks:
    -   id: reorder-python-imports
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: 4de6c8dfadef1a271a814561ce05b8bc1c446d22
    hooks:
    -   id: pylint
        entry: ./bin/run-pylint.sh
        language_version: python3
        additional_dependencies:
        - pylint-flask
