-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: adbb569fe9a64ad9bce3b53a77f1bc39ef31f682
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-added-large-files
    -   id: autopep8-wrapper
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: flake8

