version: '3'
services:
    mongodb:
        image: mongo
        restart: always
        volumes:
            - /var/knotmarker/mongodb:/data/db
        command: mongod --storageEngine wiredTiger
    webapp:
        image: truepositivelab/knotmarker
        build: .
        environment:
            KNOTMARKER_MONGODB_HOST: mongodb
            KNOTMARKER_SENTRY_DSN:
            KNOTMARKER_SECRET_KEY:
            KNOTMARKER_MAIL_PASSWORD:
            KNOTMARKER_PASSWORD_SALT:
            KNOTMARKER_DEBUG:
        links:
            - mongodb
        ports:
          - "4000:4000"
          - "5000:5000"
        volumes:
            - /var/knotmarker:/app-data
            - ./knotmarker:/app/knotmarker
#        command: gunicorn -w 1 -b 0.0.0.0:4000 knotmarker.application:app --reload --access-logfile - --error-logfile - --log-level debug
        command: python3 manage.py runserver
        restart: always
#    nginx:
#        image: nginx
#        links:
#          - webapp
#        ports:
#          - "8000:80"
#        volumes:
#          - /var/knotmarker/nginx:/etc/nginx/conf.d:ro
#        restart: always
